#ifndef SAFETYANALYSIS_GLOBAL_H
#define SAFETYANALYSIS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SAFETYANALYSIS_LIBRARY)
#define SAFETYANALYSIS_EXPORT Q_DECL_EXPORT
#else
#define SAFETYANALYSIS_EXPORT Q_DECL_IMPORT
#endif

#endif // SAFETYANALYSIS_GLOBAL_H
